# -*- coding: utf-8 -*-
"""Mean_STD_PST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aGCEhawBuaEkxUqbAOezic7GR_bcb7Lo
"""



!gdown --id 1cQlplhgnEn5yOcg8_L2-QV71Saap97lS -O filename_individuel_full_scale_0,5.spe
!gdown --id 1wUFSVJD6SsI9cCl0CkZh2fWo8QYyjdcD -O filename_individuel_full_scale_0,6.spe
!gdown --id 10VvLj7CezkLGhxVVRT0kfld7EedEv8_V -O filename_individuel_full_scale_0,7.spe
!gdown --id 1MRaMG1EpIbX9uYlrpXzQnD9WXnvSGulu -O filename_individuel_full_scale_0,8.spe
!gdown --id 1hC1u3NniaCHFY0yEt8W2WZWmTle9u_Vx -O filename_individuel_full_scale_0,9.spe
!gdown --id 15zw2rnWdlJLoC2VLLZh3WCvWSc-Snlwr -O filename_individuel_full_scale_1.spe
!gdown --id 1JXT07WdzLDUT5SkJuOv-bG6M1Tx5eiVY -O filename_individuel_full_scale_1,1.spe

"""## Modify image loading to handle multiple files

### Subtask:
Update the code to find and load images from both downloaded `.spe` files.

**Reasoning**:
Update the code to read images from both downloaded `.spe` files by iterating through a list of file paths, reading the data from each file, and combining the images into a single NumPy array.
"""

import glob
import numpy as np
import os

# Update the spe_file_path variable to be a list of filenames
spe_file_paths = ["filename_individuel_full_scale_0,5.spe", "filename_individuel_full_scale_0,6.spe", "filename_individuel_full_scale_0,7.spe", "filename_individuel_full_scale_0,8.spe","filename_individuel_full_scale_0,9.spe","filename_individuel_full_scale_1.spe","filename_individuel_full_scale_1,1.spe"]

# Dictionary to store loaded images from each file
loaded_images_dict = {}

# Assuming a simple structure where images are stacked after a header
header_size = 512  # Example header size, adjust if necessary
image_dimensions = (1024, 1024) # Assuming a fixed image size, adjust if necessary
dtype = np.uint16 # Assuming 16-bit unsigned integers
num_images_per_file = 100 # We know there are 100 images in each file

print(f"Processing {len(spe_file_paths)} files.")

# Iterate through the list of file paths
for spe_file_path in spe_file_paths:
    loaded_images_dict[spe_file_path] = [] # Create a new list for each file
    try:
        with open(spe_file_path, 'rb') as f:
            # Skip the header
            f.seek(header_size)

            # Read each image frame from the current file
            image_data_size = image_dimensions[0] * image_dimensions[1] * np.dtype(dtype).itemsize
            for i in range(num_images_per_file):
                # Read the image data for one frame
                image_data = np.fromfile(f, dtype=dtype, count=image_dimensions[0] * image_dimensions[1])
                if image_data.size != image_dimensions[0] * image_dimensions[1]:
                    print(f"Warning: Could not read expected amount of data for image {i} in file {spe_file_path}. Read {image_data.size}, expected {image_dimensions[0] * image_dimensions[1]}")
                    break # Stop if we can't read a full image from this file
                # Reshape the image data
                image_data = image_data.reshape(image_dimensions)
                image_data = image_data[:, 100:425]   # y = toutes les lignes, x = 100..499
                loaded_images_dict[spe_file_path].append(image_data)
        print(f"Successfully loaded {len(loaded_images_dict[spe_file_path])} images from {spe_file_path}.")

    except FileNotFoundError:
        print(f"Error: The file {spe_file_path} was not found.")
    except Exception as e:
        print(f"Error reading file {spe_file_path}: {e}")


# Check if any files were found for each key in the dictionary
for spe_file_path, loaded_images in loaded_images_dict.items():
    if not loaded_images:
        print(f"No images loaded from file '{spe_file_path}'")
    else:
        print(f"Loaded a total of {len(loaded_images)} images from {spe_file_path}.")
        # Convert the list of images to a NumPy array for easier processing
        loaded_images_dict[spe_file_path] = np.array(loaded_images)
        if loaded_images_dict[spe_file_path].size > 0:
            print(f"Shape of the first loaded image from {spe_file_path}: {loaded_images_dict[spe_file_path][0].shape}")
            print(f"Shape of the loaded_images_array from {spe_file_path}: {loaded_images_dict[spe_file_path].shape}")

"""## Recalculate and visualize the mean image

### Subtask:
Use the combined loaded images to calculate and display the new mean image.

**Reasoning**:
Calculate the mean of the combined loaded images and display the result using matplotlib with a title and color bar as instructed.
"""

# Dictionary to store mean images for each file
mean_images_dict = {}

# Iterate through the loaded images dictionary
for spe_file_path, loaded_images_array in loaded_images_dict.items():
    if loaded_images_array.size > 0:
        # Calculate the mean of the loaded images array along the first axis
        mean_image = np.mean(loaded_images_array, axis=0)
        mean_images_dict[spe_file_path] = mean_image
        print(f"Mean image calculated successfully for {spe_file_path}.")
        print(f"Shape of the mean image: {mean_image.shape}")
    else:
        print(f"No images loaded for {spe_file_path}, skipping mean calculation.")

import matplotlib.pyplot as plt

# Iterate through the mean images dictionary and display each one
for spe_file_path, mean_image in mean_images_dict.items():
    plt.figure(figsize=(8, 6))
    plt.imshow(mean_image, cmap='gray') # Using a grayscale colormap is typical for single channel images
    plt.title(f"Mean Image: {spe_file_path}")
    plt.colorbar(label="Intensity")
    plt.show()

print("All mean images displayed successfully.")

# Dictionary to store standard deviations for each file
std_dev_dict = {}

# Iterate through the mean images dictionary
for spe_file_path, mean_image in mean_images_dict.items():
    # Calculate the standard deviation of the mean image
    std_dev = np.std(mean_image)
    std_dev_dict[spe_file_path] = std_dev
    print(f"Standard deviation of the mean image for {spe_file_path}: {std_dev}")

# Dictionary to store standard deviation images for each file
std_dev_images_dict = {}

# Iterate through the loaded images dictionary
for spe_file_path, loaded_images_array in loaded_images_dict.items():
    if loaded_images_array.size > 0:
        # Calculate the standard deviation of the loaded images array along the first axis (across images)
        std_dev_image = np.std(loaded_images_array, axis=0)
        std_dev_images_dict[spe_file_path] = std_dev_image
        print(f"Standard deviation image calculated successfully for {spe_file_path}.")
        print(f"Shape of the standard deviation image: {std_dev_image.shape}")
    else:
        print(f"No images loaded for {spe_file_path}, skipping standard deviation image calculation.")

import matplotlib.pyplot as plt

# Iterate through the standard deviation images dictionary and display each one
for spe_file_path, std_dev_image in std_dev_images_dict.items():
    plt.figure(figsize=(8, 6))
    plt.imshow(std_dev_image, cmap='coolwarm') # Using a grayscale colormap
    plt.title(f"Standard Deviation Image: {spe_file_path}")
    plt.colorbar(label="Standard Deviation")
    plt.show()

print("All standard deviation images displayed successfully.")